version: '3'

services: 

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://dbnode:3306 -timeout 20s docker-entrypoint.sh sh -c "npm install && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - dbnode

  dbnode:
    build: 
      context: ./db
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: dbnode
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: everton/nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - dbnode
      - app

networks: 
  node-network:
    driver: bridge      